name: Flutter Build

on:
  push:
    branches: [ "main", "macos_test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.1
          channel: 'stable'
          cache: true

      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods (if needed)
        run: |
          cd ios
          pod install
          cd ..

      - name: Analyze project source
        run: dart analyze --no-fatal-warnings

      - name: Run tests
        run: flutter test --fail-fast --no-pub

      - name: Build Android APK
        run: flutter build apk --debug --no-pub

      - name: Build iOS
        run: flutter build ios --debug --no-codesign --no-pub

      - name: Build WEB
        run: flutter build web --debug --no-pub
